### ISSUE TITLE
Aborted?

### ISSUE THREAD

**Issue by hoodie** [serde-rs/yaml#6]
Hey there,
I was wondering, did you ever finish this?
Is this still WIP?

**Comment by Byron** [comment]
Hi @hoodie ,

A good question, actually. Right now, I have trouble motivating myself to do any of my ongoing projects. Right now, I'd call it 'suspended' rather than aborted though.

As there is plenty of documentation within the commit messages to indicate intend, along with recordings of all sessions that went into the project so far, I hope it proves to be rather accessible to others. Just in case somebody wants to have a go at it.

If this answers your question, please feel free to close the issue.
